# Generated by Django 4.1.4 on 2023-01-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=35)),
                ('check_todo', models.BooleanField(default=False)),
                ('datetime', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
